/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_service_reclamation (void)
{
  GtkWidget *service_reclamation;
  GtkWidget *fixed1;
  GtkWidget *bienvenue;
  GtkWidget *service_plus_rec;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *afficher_rec;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *modifier_rec;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *ajouter_rec;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *supprimer_rec;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;

  service_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (service_reclamation), _("service_reclamation"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (service_reclamation), fixed1);

  bienvenue = gtk_label_new (_("Service reclamation \n          Bienvenue"));
  gtk_widget_show (bienvenue);
  gtk_fixed_put (GTK_FIXED (fixed1), bienvenue, 184, 24);
  gtk_widget_set_size_request (bienvenue, 144, 64);

  service_plus_rec = gtk_button_new ();
  gtk_widget_show (service_plus_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), service_plus_rec, 360, 216);
  gtk_widget_set_size_request (service_plus_rec, 152, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (service_plus_rec), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Le plus reclam\303\251"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  afficher_rec = gtk_button_new ();
  gtk_widget_show (afficher_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher_rec, 200, 216);
  gtk_widget_set_size_request (afficher_rec, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (afficher_rec), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  modifier_rec = gtk_button_new ();
  gtk_widget_show (modifier_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier_rec, 304, 104);
  gtk_widget_set_size_request (modifier_rec, 104, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifier_rec), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  ajouter_rec = gtk_button_new ();
  gtk_widget_show (ajouter_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_rec, 80, 104);
  gtk_widget_set_size_request (ajouter_rec, 104, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter_rec), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  supprimer_rec = gtk_button_new ();
  gtk_widget_show (supprimer_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer_rec, 24, 216);
  gtk_widget_set_size_request (supprimer_rec, 104, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimer_rec), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) service_plus_rec, "clicked",
                    G_CALLBACK (on_service_plus_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_rec, "clicked",
                    G_CALLBACK (on_afficher_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_rec, "clicked",
                    G_CALLBACK (on_ajouter_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_rec, "clicked",
                    G_CALLBACK (on_supprimer_rec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (service_reclamation, service_reclamation, "service_reclamation");
  GLADE_HOOKUP_OBJECT (service_reclamation, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (service_reclamation, bienvenue, "bienvenue");
  GLADE_HOOKUP_OBJECT (service_reclamation, service_plus_rec, "service_plus_rec");
  GLADE_HOOKUP_OBJECT (service_reclamation, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (service_reclamation, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (service_reclamation, image5, "image5");
  GLADE_HOOKUP_OBJECT (service_reclamation, label6, "label6");
  GLADE_HOOKUP_OBJECT (service_reclamation, afficher_rec, "afficher_rec");
  GLADE_HOOKUP_OBJECT (service_reclamation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (service_reclamation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (service_reclamation, image4, "image4");
  GLADE_HOOKUP_OBJECT (service_reclamation, label5, "label5");
  GLADE_HOOKUP_OBJECT (service_reclamation, modifier_rec, "modifier_rec");
  GLADE_HOOKUP_OBJECT (service_reclamation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (service_reclamation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (service_reclamation, image2, "image2");
  GLADE_HOOKUP_OBJECT (service_reclamation, label2, "label2");
  GLADE_HOOKUP_OBJECT (service_reclamation, ajouter_rec, "ajouter_rec");
  GLADE_HOOKUP_OBJECT (service_reclamation, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (service_reclamation, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (service_reclamation, image1, "image1");
  GLADE_HOOKUP_OBJECT (service_reclamation, label1, "label1");
  GLADE_HOOKUP_OBJECT (service_reclamation, supprimer_rec, "supprimer_rec");
  GLADE_HOOKUP_OBJECT (service_reclamation, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (service_reclamation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (service_reclamation, image3, "image3");
  GLADE_HOOKUP_OBJECT (service_reclamation, label4, "label4");

  return service_reclamation;
}

GtkWidget*
create_ajouter_recl (void)
{
  GtkWidget *ajouter_recl;
  GtkWidget *fixed2;
  GtkWidget *entrytext_reclamation;
  GtkWidget *_entrynom_reclamateur;
  GtkWidget *entryprenom_reclamateur;
  GtkWidget *entrycin_reclamateur;
  GtkObject *j_adj;
  GtkWidget *j;
  GtkObject *m_adj;
  GtkWidget *m;
  GtkObject *a_adj;
  GtkWidget *a;
  GtkWidget *combobox1;
  GtkWidget *entryref_rec;
  GtkWidget *prenom_reclamateur;
  GtkWidget *nom_reclamateur;
  GtkWidget *cin_reclamateur;
  GtkWidget *type_rec;
  GtkWidget *ref_rec;
  GtkWidget *d;
  GtkWidget *text_reclamation;
  GtkWidget *retour_service_rec;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label9;
  GtkWidget *annuler_ajouter;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label8;
  GtkWidget *add_reclamation;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label25;
  GtkWidget *jours;
  GtkWidget *mois;
  GtkWidget *annee;
  GtkWidget *entry1_typerec;
  GtkWidget *type1;
  GSList *type1_group = NULL;
  GtkWidget *type2;
  GtkWidget *entry2datenaissance;

  ajouter_recl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_recl), _("Ajouter reclamation"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter_recl), fixed2);

  entrytext_reclamation = gtk_entry_new ();
  gtk_widget_show (entrytext_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), entrytext_reclamation, 192, 232);
  gtk_widget_set_size_request (entrytext_reclamation, 449, 138);
  gtk_entry_set_max_length (GTK_ENTRY (entrytext_reclamation), 5);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytext_reclamation), 8226);

  _entrynom_reclamateur = gtk_entry_new ();
  gtk_widget_show (_entrynom_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed2), _entrynom_reclamateur, 160, 8);
  gtk_widget_set_size_request (_entrynom_reclamateur, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (_entrynom_reclamateur), 8226);

  entryprenom_reclamateur = gtk_entry_new ();
  gtk_widget_show (entryprenom_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed2), entryprenom_reclamateur, 512, 8);
  gtk_widget_set_size_request (entryprenom_reclamateur, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom_reclamateur), 8226);

  entrycin_reclamateur = gtk_entry_new ();
  gtk_widget_show (entrycin_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed2), entrycin_reclamateur, 160, 72);
  gtk_widget_set_size_request (entrycin_reclamateur, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin_reclamateur), 8226);

  j_adj = gtk_adjustment_new (1, 1, 31, 1, 1, 1);
  j = gtk_spin_button_new (GTK_ADJUSTMENT (j_adj), 1, 0);
  gtk_widget_show (j);
  gtk_fixed_put (GTK_FIXED (fixed2), j, 520, 152);
  gtk_widget_set_size_request (j, 60, 27);
  gtk_widget_set_sensitive (j, FALSE);
  gtk_widget_set_extension_events (j, GDK_EXTENSION_EVENTS_CURSOR);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (j), TRUE);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (j), GTK_UPDATE_IF_VALID);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (j), TRUE);

  m_adj = gtk_adjustment_new (3, 1, 12, 1, 10, 10);
  m = gtk_spin_button_new (GTK_ADJUSTMENT (m_adj), 1, 0);
  gtk_widget_show (m);
  gtk_fixed_put (GTK_FIXED (fixed2), m, 600, 152);
  gtk_widget_set_size_request (m, 60, 27);

  a_adj = gtk_adjustment_new (2000, 1950, 2022, 1, 10, 10);
  a = gtk_spin_button_new (GTK_ADJUSTMENT (a_adj), 1, 0);
  gtk_widget_show (a);
  gtk_fixed_put (GTK_FIXED (fixed2), a, 672, 152);
  gtk_widget_set_size_request (a, 60, 27);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 216, 328);
  gtk_widget_set_size_request (combobox1, 33, 31);

  entryref_rec = gtk_entry_new ();
  gtk_widget_show (entryref_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), entryref_rec, 176, 160);
  gtk_widget_set_size_request (entryref_rec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryref_rec), 8226);

  prenom_reclamateur = gtk_label_new (_("Prenom :"));
  gtk_widget_show (prenom_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom_reclamateur, 360, 8);
  gtk_widget_set_size_request (prenom_reclamateur, 64, 24);
  gtk_label_set_line_wrap (GTK_LABEL (prenom_reclamateur), TRUE);

  nom_reclamateur = gtk_label_new (_("Nom :"));
  gtk_widget_show (nom_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed2), nom_reclamateur, 16, 16);
  gtk_widget_set_size_request (nom_reclamateur, 48, 16);
  gtk_label_set_justify (GTK_LABEL (nom_reclamateur), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (nom_reclamateur), TRUE);

  cin_reclamateur = gtk_label_new_with_mnemonic (_("CIN :"));
  gtk_widget_show (cin_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed2), cin_reclamateur, 16, 80);
  gtk_widget_set_size_request (cin_reclamateur, 40, 16);
  gtk_label_set_line_wrap (GTK_LABEL (cin_reclamateur), TRUE);

  type_rec = gtk_label_new (_("Type reclamation :"));
  gtk_widget_show (type_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), type_rec, 360, 72);
  gtk_widget_set_size_request (type_rec, 128, 24);
  gtk_label_set_line_wrap (GTK_LABEL (type_rec), TRUE);

  ref_rec = gtk_label_new (_("Reference reclamation :"));
  gtk_widget_show (ref_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), ref_rec, 8, 168);
  gtk_widget_set_size_request (ref_rec, 168, 16);

  d = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (d);
  gtk_fixed_put (GTK_FIXED (fixed2), d, 360, 152);
  gtk_widget_set_size_request (d, 136, 24);
  GTK_WIDGET_SET_FLAGS (d, GTK_CAN_FOCUS);
  gtk_label_set_line_wrap (GTK_LABEL (d), TRUE);
  gtk_label_set_selectable (GTK_LABEL (d), TRUE);

  text_reclamation = gtk_label_new (_("Texte reclamation :"));
  gtk_widget_show (text_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), text_reclamation, 24, 264);
  gtk_widget_set_size_request (text_reclamation, 152, 16);
  gtk_label_set_line_wrap (GTK_LABEL (text_reclamation), TRUE);

  retour_service_rec = gtk_button_new ();
  gtk_widget_show (retour_service_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), retour_service_rec, 400, 416);
  gtk_widget_set_size_request (retour_service_rec, 84, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (retour_service_rec), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox8), label9, FALSE, FALSE, 0);

  annuler_ajouter = gtk_button_new ();
  gtk_widget_show (annuler_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), annuler_ajouter, 494, 412);
  gtk_widget_set_size_request (annuler_ajouter, 88, 30);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (annuler_ajouter), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox7), label8, FALSE, FALSE, 0);

  add_reclamation = gtk_button_new ();
  gtk_widget_show (add_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), add_reclamation, 586, 412);
  gtk_widget_set_size_request (add_reclamation, 88, 28);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (add_reclamation), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox13), label25, FALSE, FALSE, 0);

  jours = gtk_label_new (_("J"));
  gtk_widget_show (jours);
  gtk_fixed_put (GTK_FIXED (fixed2), jours, 504, 160);
  gtk_widget_set_size_request (jours, 16, 16);

  mois = gtk_label_new (_("M"));
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 584, 160);
  gtk_widget_set_size_request (mois, 16, 16);

  annee = gtk_label_new (_("A"));
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 657, 160);
  gtk_widget_set_size_request (annee, 16, 16);

  entry1_typerec = gtk_entry_new ();
  gtk_widget_show (entry1_typerec);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_typerec, 496, 104);
  gtk_widget_set_size_request (entry1_typerec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_typerec), 8226);

  type1 = gtk_radio_button_new_with_mnemonic (NULL, _("Restaurant"));
  gtk_widget_show (type1);
  gtk_fixed_put (GTK_FIXED (fixed2), type1, 496, 72);
  gtk_widget_set_size_request (type1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (type1), type1_group);
  type1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (type1));

  type2 = gtk_radio_button_new_with_mnemonic (NULL, _("Hebergement"));
  gtk_widget_show (type2);
  gtk_fixed_put (GTK_FIXED (fixed2), type2, 624, 71);
  gtk_widget_set_size_request (type2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (type2), type1_group);
  type1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (type2));

  entry2datenaissance = gtk_entry_new ();
  gtk_widget_show (entry2datenaissance);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2datenaissance, 504, 192);
  gtk_widget_set_size_request (entry2datenaissance, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2datenaissance), 8226);

  g_signal_connect ((gpointer) retour_service_rec, "clicked",
                    G_CALLBACK (on_retour_service_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_ajouter, "clicked",
                    G_CALLBACK (on_annuler_ajoute_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_reclamation, "clicked",
                    G_CALLBACK (on_add_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) type1, "toggled",
                    G_CALLBACK (on_type1_toggled),
                    NULL);
  g_signal_connect ((gpointer) type2, "toggled",
                    G_CALLBACK (on_type2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_recl, ajouter_recl, "ajouter_recl");
  GLADE_HOOKUP_OBJECT (ajouter_recl, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter_recl, entrytext_reclamation, "entrytext_reclamation");
  GLADE_HOOKUP_OBJECT (ajouter_recl, _entrynom_reclamateur, "_entrynom_reclamateur");
  GLADE_HOOKUP_OBJECT (ajouter_recl, entryprenom_reclamateur, "entryprenom_reclamateur");
  GLADE_HOOKUP_OBJECT (ajouter_recl, entrycin_reclamateur, "entrycin_reclamateur");
  GLADE_HOOKUP_OBJECT (ajouter_recl, j, "j");
  GLADE_HOOKUP_OBJECT (ajouter_recl, m, "m");
  GLADE_HOOKUP_OBJECT (ajouter_recl, a, "a");
  GLADE_HOOKUP_OBJECT (ajouter_recl, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (ajouter_recl, entryref_rec, "entryref_rec");
  GLADE_HOOKUP_OBJECT (ajouter_recl, prenom_reclamateur, "prenom_reclamateur");
  GLADE_HOOKUP_OBJECT (ajouter_recl, nom_reclamateur, "nom_reclamateur");
  GLADE_HOOKUP_OBJECT (ajouter_recl, cin_reclamateur, "cin_reclamateur");
  GLADE_HOOKUP_OBJECT (ajouter_recl, type_rec, "type_rec");
  GLADE_HOOKUP_OBJECT (ajouter_recl, ref_rec, "ref_rec");
  GLADE_HOOKUP_OBJECT (ajouter_recl, d, "d");
  GLADE_HOOKUP_OBJECT (ajouter_recl, text_reclamation, "text_reclamation");
  GLADE_HOOKUP_OBJECT (ajouter_recl, retour_service_rec, "retour_service_rec");
  GLADE_HOOKUP_OBJECT (ajouter_recl, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajouter_recl, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajouter_recl, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter_recl, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajouter_recl, annuler_ajouter, "annuler_ajouter");
  GLADE_HOOKUP_OBJECT (ajouter_recl, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajouter_recl, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajouter_recl, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajouter_recl, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter_recl, add_reclamation, "add_reclamation");
  GLADE_HOOKUP_OBJECT (ajouter_recl, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (ajouter_recl, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ajouter_recl, image13, "image13");
  GLADE_HOOKUP_OBJECT (ajouter_recl, label25, "label25");
  GLADE_HOOKUP_OBJECT (ajouter_recl, jours, "jours");
  GLADE_HOOKUP_OBJECT (ajouter_recl, mois, "mois");
  GLADE_HOOKUP_OBJECT (ajouter_recl, annee, "annee");
  GLADE_HOOKUP_OBJECT (ajouter_recl, entry1_typerec, "entry1_typerec");
  GLADE_HOOKUP_OBJECT (ajouter_recl, type1, "type1");
  GLADE_HOOKUP_OBJECT (ajouter_recl, type2, "type2");
  GLADE_HOOKUP_OBJECT (ajouter_recl, entry2datenaissance, "entry2datenaissance");

  return ajouter_recl;
}

GtkWidget*
create_modifier_recl (void)
{
  GtkWidget *modifier_recl;
  GtkWidget *fixed3;
  GtkWidget *entryref_recl;
  GtkWidget *entrynom_reclamateur;
  GtkWidget *entryprenom_reclamateur;
  GtkWidget *entrycin_reclamateur;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *entrytext_reclamation;
  GtkWidget *nom_reclamateur;
  GtkWidget *cin_reclamateurs;
  GtkWidget *text_reclamations;
  GtkWidget *prenom_reclamateurs;
  GtkWidget *type_recl;
  GtkWidget *d;
  GtkWidget *ref_recl;
  GtkWidget *retour_service_rec;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label21;
  GtkWidget *annuler_modifier;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label22;
  GtkWidget *modify_reclamation;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label24;
  GtkWidget *type_1;
  GSList *type_1_group = NULL;
  GtkWidget *type_2;
  GtkWidget *journee;
  GtkWidget *moitier;
  GtkWidget *anneee;

  modifier_recl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_recl), _("modifier reclamation"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier_recl), fixed3);

  entryref_recl = gtk_entry_new ();
  gtk_widget_show (entryref_recl);
  gtk_fixed_put (GTK_FIXED (fixed3), entryref_recl, 296, 8);
  gtk_widget_set_size_request (entryref_recl, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryref_recl), 8226);

  entrynom_reclamateur = gtk_entry_new ();
  gtk_widget_show (entrynom_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed3), entrynom_reclamateur, 88, 64);
  gtk_widget_set_size_request (entrynom_reclamateur, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom_reclamateur), 8226);

  entryprenom_reclamateur = gtk_entry_new ();
  gtk_widget_show (entryprenom_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed3), entryprenom_reclamateur, 480, 64);
  gtk_widget_set_size_request (entryprenom_reclamateur, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom_reclamateur), 8226);

  entrycin_reclamateur = gtk_entry_new ();
  gtk_widget_show (entrycin_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed3), entrycin_reclamateur, 88, 112);
  gtk_widget_set_size_request (entrycin_reclamateur, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin_reclamateur), 8226);

  jour_adj = gtk_adjustment_new (1, 31, 100, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed3), jour, 496, 168);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed3), mois, 576, 168);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 1950, 2022, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed3), annee, 664, 168);
  gtk_widget_set_size_request (annee, 60, 27);

  entrytext_reclamation = gtk_entry_new ();
  gtk_widget_show (entrytext_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), entrytext_reclamation, 200, 264);
  gtk_widget_set_size_request (entrytext_reclamation, 368, 128);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytext_reclamation), 8226);

  nom_reclamateur = gtk_label_new (_("Nom :"));
  gtk_widget_show (nom_reclamateur);
  gtk_fixed_put (GTK_FIXED (fixed3), nom_reclamateur, 32, 64);
  gtk_widget_set_size_request (nom_reclamateur, 57, 25);

  cin_reclamateurs = gtk_label_new (_("CIN :"));
  gtk_widget_show (cin_reclamateurs);
  gtk_fixed_put (GTK_FIXED (fixed3), cin_reclamateurs, 32, 120);
  gtk_widget_set_size_request (cin_reclamateurs, 49, 17);

  text_reclamations = gtk_label_new (_("Texte reclamation :"));
  gtk_widget_show (text_reclamations);
  gtk_fixed_put (GTK_FIXED (fixed3), text_reclamations, 24, 288);
  gtk_widget_set_size_request (text_reclamations, 160, 24);

  prenom_reclamateurs = gtk_label_new (_("Prenom :"));
  gtk_widget_show (prenom_reclamateurs);
  gtk_fixed_put (GTK_FIXED (fixed3), prenom_reclamateurs, 320, 56);
  gtk_widget_set_size_request (prenom_reclamateurs, 72, 24);

  type_recl = gtk_label_new (_("Type reclamation :"));
  gtk_widget_show (type_recl);
  gtk_fixed_put (GTK_FIXED (fixed3), type_recl, 376, 88);
  gtk_widget_set_size_request (type_recl, 200, 381);

  d = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (d);
  gtk_fixed_put (GTK_FIXED (fixed3), d, 328, 168);
  gtk_widget_set_size_request (d, 128, 24);

  ref_recl = gtk_label_new (_("Reference reclamation :"));
  gtk_widget_show (ref_recl);
  gtk_fixed_put (GTK_FIXED (fixed3), ref_recl, 120, 8);
  gtk_widget_set_size_request (ref_recl, 160, 24);

  retour_service_rec = gtk_button_new ();
  gtk_widget_show (retour_service_rec);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_service_rec, 408, 440);
  gtk_widget_set_size_request (retour_service_rec, 80, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (retour_service_rec), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox9), label21, FALSE, FALSE, 0);

  annuler_modifier = gtk_button_new ();
  gtk_widget_show (annuler_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), annuler_modifier, 496, 440);
  gtk_widget_set_size_request (annuler_modifier, 80, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (annuler_modifier), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox10), label22, FALSE, FALSE, 0);

  modify_reclamation = gtk_button_new ();
  gtk_widget_show (modify_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), modify_reclamation, 584, 440);
  gtk_widget_set_size_request (modify_reclamation, 88, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (modify_reclamation), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox12), label24, FALSE, FALSE, 0);

  type_1 = gtk_radio_button_new_with_mnemonic (NULL, _("Restaurant"));
  gtk_widget_show (type_1);
  gtk_fixed_put (GTK_FIXED (fixed3), type_1, 496, 104);
  gtk_widget_set_size_request (type_1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (type_1), type_1_group);
  type_1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (type_1));

  type_2 = gtk_radio_button_new_with_mnemonic (NULL, _("Hebergement"));
  gtk_widget_show (type_2);
  gtk_fixed_put (GTK_FIXED (fixed3), type_2, 616, 104);
  gtk_widget_set_size_request (type_2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (type_2), type_1_group);
  type_1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (type_2));

  journee = gtk_label_new (_("J"));
  gtk_widget_show (journee);
  gtk_fixed_put (GTK_FIXED (fixed3), journee, 480, 176);
  gtk_widget_set_size_request (journee, 16, 16);

  moitier = gtk_label_new (_("M"));
  gtk_widget_show (moitier);
  gtk_fixed_put (GTK_FIXED (fixed3), moitier, 560, 176);
  gtk_widget_set_size_request (moitier, 16, 16);

  anneee = gtk_label_new (_("A"));
  gtk_widget_show (anneee);
  gtk_fixed_put (GTK_FIXED (fixed3), anneee, 648, 176);
  gtk_widget_set_size_request (anneee, 16, 16);

  g_signal_connect ((gpointer) retour_service_rec, "clicked",
                    G_CALLBACK (on_retour_service_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_modifier, "clicked",
                    G_CALLBACK (on_annuler_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) modify_reclamation, "clicked",
                    G_CALLBACK (on_modify_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) type_1, "toggled",
                    G_CALLBACK (on_type_1_toggled),
                    NULL);
  g_signal_connect ((gpointer) type_2, "toggled",
                    G_CALLBACK (on_type_2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_recl, modifier_recl, "modifier_recl");
  GLADE_HOOKUP_OBJECT (modifier_recl, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier_recl, entryref_recl, "entryref_recl");
  GLADE_HOOKUP_OBJECT (modifier_recl, entrynom_reclamateur, "entrynom_reclamateur");
  GLADE_HOOKUP_OBJECT (modifier_recl, entryprenom_reclamateur, "entryprenom_reclamateur");
  GLADE_HOOKUP_OBJECT (modifier_recl, entrycin_reclamateur, "entrycin_reclamateur");
  GLADE_HOOKUP_OBJECT (modifier_recl, jour, "jour");
  GLADE_HOOKUP_OBJECT (modifier_recl, mois, "mois");
  GLADE_HOOKUP_OBJECT (modifier_recl, annee, "annee");
  GLADE_HOOKUP_OBJECT (modifier_recl, entrytext_reclamation, "entrytext_reclamation");
  GLADE_HOOKUP_OBJECT (modifier_recl, nom_reclamateur, "nom_reclamateur");
  GLADE_HOOKUP_OBJECT (modifier_recl, cin_reclamateurs, "cin_reclamateurs");
  GLADE_HOOKUP_OBJECT (modifier_recl, text_reclamations, "text_reclamations");
  GLADE_HOOKUP_OBJECT (modifier_recl, prenom_reclamateurs, "prenom_reclamateurs");
  GLADE_HOOKUP_OBJECT (modifier_recl, type_recl, "type_recl");
  GLADE_HOOKUP_OBJECT (modifier_recl, d, "d");
  GLADE_HOOKUP_OBJECT (modifier_recl, ref_recl, "ref_recl");
  GLADE_HOOKUP_OBJECT (modifier_recl, retour_service_rec, "retour_service_rec");
  GLADE_HOOKUP_OBJECT (modifier_recl, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier_recl, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier_recl, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier_recl, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifier_recl, annuler_modifier, "annuler_modifier");
  GLADE_HOOKUP_OBJECT (modifier_recl, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier_recl, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier_recl, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier_recl, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifier_recl, modify_reclamation, "modify_reclamation");
  GLADE_HOOKUP_OBJECT (modifier_recl, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier_recl, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modifier_recl, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier_recl, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier_recl, type_1, "type_1");
  GLADE_HOOKUP_OBJECT (modifier_recl, type_2, "type_2");
  GLADE_HOOKUP_OBJECT (modifier_recl, journee, "journee");
  GLADE_HOOKUP_OBJECT (modifier_recl, moitier, "moitier");
  GLADE_HOOKUP_OBJECT (modifier_recl, anneee, "anneee");

  return modifier_recl;
}

GtkWidget*
create_supprimer_recl (void)
{
  GtkWidget *supprimer_recl;
  GtkWidget *fixed4;
  GtkWidget *entryref_reclamation;
  GtkWidget *ref_reclamation;
  GtkWidget *annuler_supprimer;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label28;
  GtkWidget *supprimer_reclamation;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label29;
  GtkWidget *retour_service_reclamation;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label27;

  supprimer_recl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_recl), _("Supprimer reclamation"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimer_recl), fixed4);

  entryref_reclamation = gtk_entry_new ();
  gtk_widget_show (entryref_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), entryref_reclamation, 256, 16);
  gtk_widget_set_size_request (entryref_reclamation, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryref_reclamation), 8226);

  ref_reclamation = gtk_label_new (_("Reference reclamation :"));
  gtk_widget_show (ref_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), ref_reclamation, 56, 8);
  gtk_widget_set_size_request (ref_reclamation, 169, 33);

  annuler_supprimer = gtk_button_new ();
  gtk_widget_show (annuler_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), annuler_supprimer, 208, 208);
  gtk_widget_set_size_request (annuler_supprimer, 98, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (annuler_supprimer), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox15), label28, FALSE, FALSE, 0);

  supprimer_reclamation = gtk_button_new ();
  gtk_widget_show (supprimer_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer_reclamation, 320, 208);
  gtk_widget_set_size_request (supprimer_reclamation, 112, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (supprimer_reclamation), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox16), label29, FALSE, FALSE, 0);

  retour_service_reclamation = gtk_button_new ();
  gtk_widget_show (retour_service_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), retour_service_reclamation, 88, 210);
  gtk_widget_set_size_request (retour_service_reclamation, 102, 27);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (retour_service_reclamation), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox14), label27, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annuler_supprimer, "clicked",
                    G_CALLBACK (on_annuler_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_reclamation, "clicked",
                    G_CALLBACK (on_supprimer_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_service_reclamation, "clicked",
                    G_CALLBACK (on_retour_service_rec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_recl, supprimer_recl, "supprimer_recl");
  GLADE_HOOKUP_OBJECT (supprimer_recl, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimer_recl, entryref_reclamation, "entryref_reclamation");
  GLADE_HOOKUP_OBJECT (supprimer_recl, ref_reclamation, "ref_reclamation");
  GLADE_HOOKUP_OBJECT (supprimer_recl, annuler_supprimer, "annuler_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer_recl, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (supprimer_recl, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (supprimer_recl, image15, "image15");
  GLADE_HOOKUP_OBJECT (supprimer_recl, label28, "label28");
  GLADE_HOOKUP_OBJECT (supprimer_recl, supprimer_reclamation, "supprimer_reclamation");
  GLADE_HOOKUP_OBJECT (supprimer_recl, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (supprimer_recl, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (supprimer_recl, image16, "image16");
  GLADE_HOOKUP_OBJECT (supprimer_recl, label29, "label29");
  GLADE_HOOKUP_OBJECT (supprimer_recl, retour_service_reclamation, "retour_service_reclamation");
  GLADE_HOOKUP_OBJECT (supprimer_recl, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (supprimer_recl, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (supprimer_recl, image14, "image14");
  GLADE_HOOKUP_OBJECT (supprimer_recl, label27, "label27");

  return supprimer_recl;
}

GtkWidget*
create_afficher_recl (void)
{
  GtkWidget *afficher_recl;
  GtkWidget *fixed5;
  GtkWidget *tab_affich;
  GtkWidget *annuler_recla;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label31;
  GtkWidget *retour_recla;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label30;

  afficher_recl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher_recl), _("Afficher"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (afficher_recl), fixed5);

  tab_affich = gtk_tree_view_new ();
  gtk_widget_show (tab_affich);
  gtk_fixed_put (GTK_FIXED (fixed5), tab_affich, 72, 24);
  gtk_widget_set_size_request (tab_affich, 300, 200);

  annuler_recla = gtk_button_new ();
  gtk_widget_show (annuler_recla);
  gtk_fixed_put (GTK_FIXED (fixed5), annuler_recla, 296, 256);
  gtk_widget_set_size_request (annuler_recla, 88, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (annuler_recla), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox18), label31, FALSE, FALSE, 0);

  retour_recla = gtk_button_new ();
  gtk_widget_show (retour_recla);
  gtk_fixed_put (GTK_FIXED (fixed5), retour_recla, 200, 256);
  gtk_widget_set_size_request (retour_recla, 90, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (retour_recla), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox17), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) tab_affich, "row_activated",
                    G_CALLBACK (on_tab_affich_row_activated),
                    NULL);
  g_signal_connect ((gpointer) annuler_recla, "clicked",
                    G_CALLBACK (on_annuler_recla_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_recla, "clicked",
                    G_CALLBACK (on_retour_recla_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher_recl, afficher_recl, "afficher_recl");
  GLADE_HOOKUP_OBJECT (afficher_recl, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (afficher_recl, tab_affich, "tab_affich");
  GLADE_HOOKUP_OBJECT (afficher_recl, annuler_recla, "annuler_recla");
  GLADE_HOOKUP_OBJECT (afficher_recl, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (afficher_recl, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (afficher_recl, image18, "image18");
  GLADE_HOOKUP_OBJECT (afficher_recl, label31, "label31");
  GLADE_HOOKUP_OBJECT (afficher_recl, retour_recla, "retour_recla");
  GLADE_HOOKUP_OBJECT (afficher_recl, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (afficher_recl, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (afficher_recl, image17, "image17");
  GLADE_HOOKUP_OBJECT (afficher_recl, label30, "label30");

  return afficher_recl;
}

GtkWidget*
create_leplus_recl (void)
{
  GtkWidget *leplus_recl;
  GtkWidget *fixed6;
  GtkWidget *ser_plus_rec;
  GtkWidget *plus_rec;
  GtkWidget *annuler_ser_recl;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label34;

  leplus_recl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (leplus_recl), _("service le plus reclam\303\251 :"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (leplus_recl), fixed6);

  ser_plus_rec = gtk_label_new (_("service plus rec :"));
  gtk_widget_show (ser_plus_rec);
  gtk_fixed_put (GTK_FIXED (fixed6), ser_plus_rec, 88, 104);
  gtk_widget_set_size_request (ser_plus_rec, 264, 24);
  gtk_label_set_line_wrap (GTK_LABEL (ser_plus_rec), TRUE);

  plus_rec = gtk_label_new (_("le service le plus reclame"));
  gtk_widget_show (plus_rec);
  gtk_fixed_put (GTK_FIXED (fixed6), plus_rec, 104, 32);
  gtk_widget_set_size_request (plus_rec, 216, 24);

  annuler_ser_recl = gtk_button_new ();
  gtk_widget_show (annuler_ser_recl);
  gtk_fixed_put (GTK_FIXED (fixed6), annuler_ser_recl, 240, 216);
  gtk_widget_set_size_request (annuler_ser_recl, 104, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (annuler_ser_recl), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox19), label34, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annuler_ser_recl, "clicked",
                    G_CALLBACK (on_annuler_ser_recl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (leplus_recl, leplus_recl, "leplus_recl");
  GLADE_HOOKUP_OBJECT (leplus_recl, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (leplus_recl, ser_plus_rec, "ser_plus_rec");
  GLADE_HOOKUP_OBJECT (leplus_recl, plus_rec, "plus_rec");
  GLADE_HOOKUP_OBJECT (leplus_recl, annuler_ser_recl, "annuler_ser_recl");
  GLADE_HOOKUP_OBJECT (leplus_recl, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (leplus_recl, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (leplus_recl, image19, "image19");
  GLADE_HOOKUP_OBJECT (leplus_recl, label34, "label34");

  return leplus_recl;
}

