/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_service_reclamation (void);
GtkWidget* create_ajouter_recl (void);
GtkWidget* create_modifier_recl (void);
GtkWidget* create_supprimer_recl (void);
GtkWidget* create_afficher_recl (void);
GtkWidget* create_leplus_recl (void);
