/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *service_reclamation;
  GtkWidget *ajouter_recl;
  GtkWidget *modifier_recl;
  GtkWidget *supprimer_recl;
  GtkWidget *afficher_recl;
  GtkWidget *leplus_recl;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //service_reclamation = create_service_reclamation ();
  //gtk_widget_show (service_reclamation);
  ajouter_recl = create_ajouter_recl ();
  gtk_widget_show (ajouter_recl);
  //modifier_recl = create_modifier_recl ();
  //gtk_widget_show (modifier_recl);
  //supprimer_recl = create_supprimer_recl ();
  //gtk_widget_show (supprimer_recl);
  afficher_recl = create_afficher_recl ();
  gtk_widget_show (afficher_recl);
  //leplus_recl = create_leplus_recl ();
  //gtk_widget_show (leplus_recl);

  gtk_main ();
  return 0;
}

